import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Song Lyrics - Charles Jasema | Gospel Music Lyrics',
  description: 'Read and download lyrics for all Charles Jasema worship songs. Contemporary gospel music with messages of faith, hope, and love. Search, read, and sing along to Mercy, A Call, My Help Comes From The Lord, I Don\'t Belong Here, Jesus You Are Lord, Nyadru - Love, Where Will You Be, and more.',
  keywords: [
    'Charles Jasema lyrics',
    'gospel lyrics',
    'worship song lyrics',
    'Christian music lyrics',
    'contemporary gospel',
    'Mercy lyrics',
    'A Call lyrics',
    'My Help Comes From The Lord lyrics',
    'I Don\'t Belong Here lyrics',
    'Jesus You Are Lord lyrics',
    'Nyadru Love lyrics',
    'Where Will You Be lyrics',
    'Kuyeyeju lyrics',
    'I Am Alive in You lyrics',
    'Charles Jasema music',
    'gospel music Uganda',
    'South Sudan gospel artist',
    'worship lyrics download',
    'Christian song lyrics',
  ],
  authors: [{ name: 'Charles Jasema' }],
  creator: 'Charles Jasema',
  publisher: 'Charles Jasema',
  openGraph: {
    title: 'Song Lyrics - Charles Jasema | Gospel Music Lyrics',
    description: 'Read and download lyrics for all Charles Jasema worship songs. Contemporary gospel music with messages of faith, hope, and love.',
    type: 'website',
    locale: 'en_US',
    siteName: 'Charles Jasema',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Song Lyrics - Charles Jasema',
    description: 'Read and download lyrics for all Charles Jasema worship songs',
    creator: '@JasemaMusic',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};
