/**
 * Blog Content Configuration
 * 
 * ⚠️ ADMIN: Edit this file to update your blog articles
 * Add, remove, or modify blog posts without touching the page code.
 * 
 * Instructions:
 * - category: 'software' | 'design' | 'music' | 'personal' | 'tutorial'
 * - tags: Array of relevant tags for filtering
 * - featured: true/false (featured articles appear at the top)
 * - readTime: Estimated reading time in minutes
 */

export const blogConfig = {
  // Blog Page Header
  header: {
    title: 'Blog',
    subtitle: 'Thoughts, tutorials, and insights on software development, design, and music ministry',
  },

  // Blog Categories
  categories: [
    { id: 'all', label: 'All Articles', color: 'primary-gold' },
    { id: 'software', label: 'Software Development', color: 'primary-gold' },
    { id: 'design', label: 'Design', color: 'tech-teal' },
    { id: 'music', label: 'Music Ministry', color: 'accent-red' },
    { id: 'tutorial', label: 'Tutorials', color: 'primary-gold' },
    { id: 'personal', label: 'Personal', color: 'tech-teal' },
  ],

  // Blog Articles
  articles: [
    {
      id: '1',
      title: 'Building Scalable Web Applications with Next.js 14',
      slug: 'building-scalable-web-apps-nextjs-14',
      category: 'software' as const,
      excerpt: 'Learn how to build performant and scalable web applications using Next.js 14 with App Router, Server Components, and modern best practices.',
      content: '', // Full content will be added later
      author: 'Charles Jasema',
      publishDate: '2024-03-15',
      readTime: 8,
      tags: ['Next.js', 'React', 'Web Development', 'TypeScript'],
      image: '/placeholder',
      featured: true,
    },
    {
      id: '2',
      title: 'The Art of UI/UX Design: Creating Intuitive Interfaces',
      slug: 'art-of-ui-ux-design',
      category: 'design' as const,
      excerpt: 'Explore the principles of great UI/UX design and learn how to create interfaces that users love. From wireframes to final designs.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-03-10',
      readTime: 6,
      tags: ['UI/UX', 'Design', 'Figma', 'User Experience'],
      image: '/placeholder',
      featured: true,
    },
    {
      id: '3',
      title: 'Leading Worship: Lessons from 6 Years of Ministry',
      slug: 'leading-worship-lessons',
      category: 'music' as const,
      excerpt: 'Reflections and practical lessons learned from leading worship in various settings. How to create meaningful worship experiences.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-03-05',
      readTime: 5,
      tags: ['Worship', 'Ministry', 'Music', 'Leadership'],
      image: '/placeholder',
      featured: true,
    },
    {
      id: '4',
      title: 'TypeScript Best Practices for Large-Scale Applications',
      slug: 'typescript-best-practices',
      category: 'software' as const,
      excerpt: 'Essential TypeScript patterns and practices for building maintainable large-scale applications. Type safety, generics, and more.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-02-28',
      readTime: 10,
      tags: ['TypeScript', 'JavaScript', 'Best Practices', 'Programming'],
      image: '/placeholder',
      featured: false,
    },
    {
      id: '5',
      title: 'Creating a Brand Identity: From Concept to Execution',
      slug: 'creating-brand-identity',
      category: 'design' as const,
      excerpt: 'A step-by-step guide to creating compelling brand identities. Logo design, color theory, typography, and brand guidelines.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-02-20',
      readTime: 7,
      tags: ['Branding', 'Design', 'Logo Design', 'Identity'],
      image: '/placeholder',
      featured: false,
    },
    {
      id: '6',
      title: 'Songwriting for Worship: Crafting Meaningful Lyrics',
      slug: 'songwriting-for-worship',
      category: 'music' as const,
      excerpt: 'Tips and techniques for writing worship songs that connect with people and glorify God. From inspiration to final composition.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-02-15',
      readTime: 6,
      tags: ['Songwriting', 'Worship', 'Music', 'Creativity'],
      image: '/placeholder',
      featured: false,
    },
    {
      id: '7',
      title: 'Getting Started with React Hooks: A Complete Guide',
      slug: 'react-hooks-complete-guide',
      category: 'tutorial' as const,
      excerpt: 'Master React Hooks with this comprehensive guide. Learn useState, useEffect, useContext, and custom hooks with practical examples.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-02-10',
      readTime: 12,
      tags: ['React', 'Hooks', 'Tutorial', 'JavaScript'],
      image: '/placeholder',
      featured: false,
    },
    {
      id: '8',
      title: 'My Journey: From Code to Worship',
      slug: 'journey-code-to-worship',
      category: 'personal' as const,
      excerpt: 'A personal story of how I balance my passion for software development with my calling to worship ministry. Lessons learned along the way.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-02-05',
      readTime: 5,
      tags: ['Personal', 'Journey', 'Ministry', 'Career'],
      image: '/placeholder',
      featured: false,
    },
    {
      id: '9',
      title: 'Responsive Design Patterns for Modern Web Apps',
      slug: 'responsive-design-patterns',
      category: 'design' as const,
      excerpt: 'Essential responsive design patterns and techniques for creating beautiful, mobile-friendly web applications that work on any device.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-01-30',
      readTime: 8,
      tags: ['Responsive Design', 'CSS', 'Mobile', 'Web Design'],
      image: '/placeholder',
      featured: false,
    },
    {
      id: '10',
      title: 'Building a REST API with Node.js and Express',
      slug: 'building-rest-api-nodejs',
      category: 'tutorial' as const,
      excerpt: 'Learn how to build a production-ready REST API using Node.js, Express, and MongoDB. Authentication, validation, and best practices included.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-01-25',
      readTime: 15,
      tags: ['Node.js', 'Express', 'API', 'Backend', 'Tutorial'],
      image: '/placeholder',
      featured: false,
    },
    {
      id: '11',
      title: 'The Power of Music in Ministry',
      slug: 'power-of-music-in-ministry',
      category: 'music' as const,
      excerpt: 'Exploring how music transforms worship experiences and connects people with God. Biblical foundations and practical applications.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-01-20',
      readTime: 6,
      tags: ['Music', 'Ministry', 'Worship', 'Theology'],
      image: '/placeholder',
      featured: false,
    },
    {
      id: '12',
      title: 'Mastering Git: Advanced Workflows and Tips',
      slug: 'mastering-git-advanced-workflows',
      category: 'software' as const,
      excerpt: 'Take your Git skills to the next level with advanced workflows, branching strategies, and productivity tips for professional development.',
      content: '',
      author: 'Charles Jasema',
      publishDate: '2024-01-15',
      readTime: 9,
      tags: ['Git', 'Version Control', 'DevOps', 'Workflow'],
      image: '/placeholder',
      featured: false,
    },
  ],
} as const;

export type BlogArticle = typeof blogConfig.articles[number];
export type BlogCategory = 'all' | 'software' | 'design' | 'music' | 'tutorial' | 'personal';
