import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Music Ministry - Charles Jasema | Gospel Artist & Worship Leader',
  description: 'Explore Charles Jasema\'s music ministry - 12 singles, music videos, and worship songs. Contemporary gospel artist from South Sudan spreading hope through worship since 2015. Listen on Mdundo, YouTube, Spotify, and Apple Music.',
  keywords: [
    'Charles Jasema music',
    'gospel artist',
    'worship leader',
    'contemporary gospel',
    'Christian music',
    'South Sudan gospel',
    'Uganda gospel artist',
    'worship songs',
    'gospel music videos',
    'Kuyeyeju',
    'I Am Alive in You',
    'Where Will You Be',
    'Mercy',
    'A Call',
    'My Help Comes From The Lord',
    'I Don\'t Belong Here',
    'Jesus You Are Lord',
    'Nyadru Love',
    'Charles Jasema Mdundo',
    'Charles Jasema YouTube',
    'gospel music streaming',
    'worship music download',
  ],
  authors: [{ name: 'Charles Jasema' }],
  creator: 'Charles Jasema',
  publisher: 'Charles Jasema',
  openGraph: {
    title: 'Music Ministry - Charles Jasema | Gospel Artist',
    description: 'Explore Charles Jasema\'s music ministry - 12 singles, music videos, and worship songs. Contemporary gospel spreading hope through worship since 2015.',
    type: 'music.musician',
    locale: 'en_US',
    siteName: 'Charles Jasema',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Music Ministry - Charles Jasema',
    description: 'Contemporary gospel artist spreading hope through worship since 2015',
    creator: '@JasemaMusic',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};
